// Code generated by sqlc. DO NOT EDIT.

package logprocess

import (
	"database/sql"
	"time"
)

type Record struct {
	ID             int64
	ConsumerID     string
	UpstreamUri    string
	ResponseID     int64
	RequestID      int64
	RouteID        string
	ServiceID      string
	ProxyLatency   int64
	GatewayLatency int64
	RequestLatency int64
	ClientIp       string
	StartedAt      time.Time
}

type Request struct {
	ID              int64
	Method          string
	Uri             string
	Url             string
	Size            string
	HeaderAccept    sql.NullString
	HeaderHost      sql.NullString
	HeaderUserAgent sql.NullString
}

type Response struct {
	ID                            int64
	Status                        int64
	Size                          string
	ContentLength                 string
	Via                           string
	Connection                    string
	AccessControlAllowCredentials string
	AccessControlAllowOrigin      string
	ContentType                   string
	Server                        string
}

type Route struct {
	ID            string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Hosts         string
	Methods       string
	PreserveHost  int32
	Protocols     string
	RegexPriority int64
	ServiceID     int64
	StripPath     int32
}

type Service struct {
	ID           string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Host         string
	Name         string
	Path         string
	Port         int64
	Protocol     string
	ReadTimeout  int64
	WriteTimeout int64
	Reties       int64
}
