// Code generated by sqlc. DO NOT EDIT.

package mysql

import (
	"time"
)

type Record struct {
	ID             int64
	ConsumerID     string
	UpstreamUri    string
	ResponseID     string
	RequestID      string
	RouteID        string
	ServiceID      string
	ProxyLatency   int64
	GatewayLatency int64
	RequestLatency int64
	ClientIp       string
	StartedAt      time.Time
}

type Request struct {
	ID              string
	Method          string
	Uri             string
	Url             string
	Size            int64
	Querystring     string
	HeaderAccept    string
	HeaderHost      string
	HeaderUserAgent string
}

type Response struct {
	ID                            string
	Status                        int64
	Size                          int64
	ContentLength                 int64
	Via                           string
	Connection                    string
	AccessControlAllowCredentials string
	AccessControlAllowOrigin      string
	ContentType                   string
	Server                        string
}

type Route struct {
	ID            string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Hosts         string
	Methods       string
	Paths         string
	PreserveHost  int32
	Protocols     string
	RegexPriority int64
	ServiceID     string
	StripPath     int32
}

type Service struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Host           string
	Name           string
	Path           string
	Port           int64
	Protocol       string
	ReadTimeout    int64
	WriteTimeout   int64
	ConnectTimeout int64
	Retries        int64
}
